### ISSUE TITLE
Build Errors.

### ISSUE THREAD

**Issue by veer9002** [maxep/MXSegmentedControl#1]
I am using xcode 9 and swift 4.I am using cocoapods to install this library. When I build the project I got following error.
         1- Method 'set(title:for:)' with Objective-C selector 'setWithTitle:for:' conflicts with previous declaration with the same Objective-C selector
         2- Cannot assign to property: 'selectedIndex' setter is inaccessible.

**Comment by maxep** [comment]
1. I dont have any build error when using XC9, Swift4 and CocoaPods.
What says the error exactly and what is the code that raise it?
2. To select an index, please use the method: `func select(index: Int, animated: Bool)`
