### ISSUE TITLE
How can i set width based on segment title?

### ISSUE THREAD

**Issue by bhavikvwteam** [maxep/MXSegmentedControl#25]
In attached screenshot you can see segment title is getting cut from middle due to large title. How can i make sure that it does not get cut by applying segment width based on text?

![Screenshot 2020-12-30 at 12 25 10 PM](https://user-images.githubusercontent.com/72979738/103335179-451ed680-4a9a-11eb-83b9-69ddca806486.png)

**Comment by Crying-Goose** [comment]
I'm looking for a way. 
First of all, I'm trying to extend the MXSegmentedControl.

**Comment by maxep** [comment]
That should be working by default!
If you do not set the `segmentControl.segmentWidth` property, the width is computed according the content. Do you have a code snippet to share?
