### ISSUE TITLE
Manually set index of segment

### ISSUE THREAD

**Issue by ruchitshahP16it** [maxep/MXSegmentedControl#26]
Hi 

I had added MXSegmentedcontrol in my app, I want to know by default how to display 2nd index/segment. Also want to know at the view controller side I had selected 4th index/segment and navigate to another controller while coming back on same controller at that time its value set at 4th index/segment but it shows first index/segment data. please let me know how to set first index/segment , which method will be used. 
I had shared video please check.

Thanks 

https://user-images.githubusercontent.com/62236553/110892049-4f224880-8319-11eb-8ba7-0810bf28bd23.MP4

**Comment by maxep** [comment]
This doesnt look like an issue in `MXSegmentedControl` but in your app. I suggest you use StackOverflow for better help.
