### ISSUE TITLE
Faild to render and update auto layout

### ISSUE THREAD

**Issue by AminFadul** [maxep/MXSegmentedControl#4]
I keep getting this error messages since I installed it 

bella_ios/Baqshish/Baqshish/Providers.storyboard: error: IB Designables: Failed to render and update auto layout status for HyperRestaurantVC (gvV-JS-DRg): dlopen(MXSegmentedControl.framework, 1): no suitable image found.  Did find:
	MXSegmentedControl.framework: required code signature missing for 'MXSegmentedControl.framework'

![screen shot 2018-09-16 at 1 02 45 pm](https://user-images.githubusercontent.com/29886596/45595236-53bc4f00-b9b1-11e8-9c95-d6ae195172ee.png)
![screen shot 2018-09-16 at 1 02 50 pm](https://user-images.githubusercontent.com/29886596/45595237-53bc4f00-b9b1-11e8-94d3-0a0f415d189e.png)

what have I tried 

- clean rebuild
- close Xcode
- restart the OS (worked for a while)

Xcode 9.4 
Swift 4

**Comment by maxep** [comment]
This could help: https://stackoverflow.com/questions/39732312/xcode-8-ib-designables-failed-to-render-and-update-auto-layout-status-the-a
