### ISSUE TITLE
Give Swift Compiler Error for latest updates

### ISSUE THREAD

**Issue by mohsinka** [maxep/MXSegmentedControl#6]
Hello,

Thanks for your great work on implementing this library. We are using it in our application. But with the new Swift 4.2, Mojave OS and xCode 10 the library breaks. Could you please do a new release with the latest code base?

Thanks very much for your help.

**Comment by impul** [comment]
@mohsinka, I already made [PR,](https://github.com/maxep/MXSegmentedControl/pull/5). @maxep , you just need to merge it and update podspec.

**Comment by mohsinka** [comment]
@maxep Please update?

**Comment by maxep** [comment]
Hi, version 1.0.0 is now available with swift 4.2 support!

**Comment by mohsinka** [comment]
Yayy! Thanks :)
